# Generated by Django 2.1.10 on 2022-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul', '0002_auto_20220503_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
